plugins:
  - awesome-pages
  - include-markdown

site_name: FlagGems
theme:
  name: material
  language: en
  features:
    - content.code.copy

markdown_extensions:
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences

docs_dir: docs

nav:
  - Introduction: index.md
  - Features: features.md
  - Getting Started: getting-started.md
  - Installation: installation.md
  - Pointwise Dynamic: pointwise_dynamic.md
  - Python Tests: pytest_in_flaggems.md
  - C++ Tests: ctest_in_flaggems.md
  - Operator List: operators.md
  - Performance: performance_and_benchmark.md
  - Countributing: contribution.md
  - Add A C++ wrapper: add_a_cpp_wrapper.md
