name: test-context

on:
  workflow_run:
    workflows:
      - code-format-check
    types:
      - completed

jobs:
  blahblah:
    runs-on: jiuding
    steps:
      - id: first
        uses: actions/checkout@v6
        with:
          ref: gh-pages
          token: ${{ secrets.MY_TOKEN }}
